# Generated by Django 3.1.6 on 2021-06-28 10:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='messageDate',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
