# Generated by Django 3.1.6 on 2021-06-28 10:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_feedback_messagedate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='messageDate',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
