# Generated by Django 3.1.6 on 2021-06-28 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20210628_1541'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='subject',
            field=models.CharField(default='Improvements', max_length=250),
        ),
    ]
