# Generated by Django 3.1.6 on 2021-07-08 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_feedback_subject'),
    ]

    operations = [
        migrations.CreateModel(
            name='projects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projectName', models.CharField(max_length=200)),
                ('projectDescription', models.TextField(max_length=650)),
                ('projectImage', models.ImageField(upload_to='projectInfo/')),
                ('projectLink', models.URLField()),
            ],
        ),
    ]
